# 250218.md
## Bug
- code 
```python
# models/controlnet_union.py line 915
else:
    sample, res_samples = downsample_block(hidden_states=sample, temb=emb) # BUG
```
- error
```
RuntimeError: The size of tensor a (32) must match the size of tensor b (320) at non-singleton dimension 4
```
## Check
- inconsistent image shape between input and required
```
# ours
-> sample, res_samples = downsample_block(hidden_states=sample, temb=emb) # BUG
(Pdb) sample.shape
torch.Size([2, 320, 32, 32])

# inference
-> sample, res_samples = downsample_block(hidden_states=sample, temb=emb) # BUG
(Pdb) sample.shape
torch.Size([2, 320, 126, 126])
```
- possible bug in latent preparation `promax/controlnet_union_train_medical_image_restoration.py` `line 1389`
```
## when passing to forward() 
```
## Solved; Now can proceed to training
- but encounter CUDA out of memory problem `models/controlnet_union.py(927)`

## BUG
- unmatched type: 
```python
model_pred = unet(
    noisy_latents,
    timesteps.squeeze(0),
    encoder_hidden_states=hidden_states.to(accelerator.device),
    added_cond_kwargs=controlnet_added_cond_kwargs,
    down_block_additional_residuals=down_block_res_samples,
    mid_block_additional_residual=mid_block_res_sample.to(dtype=weight_dtype),
    return_dict=False,
)[0]
```
- error
```
Traceback (most recent call last):
  File "/home/heming/research/medical/ControlNetPlus/promax/controlnet_union_train_medical_image_restoration_fix_controlnet.py", line 2044, in <module>
    main(args)
  File "/home/heming/research/medical/ControlNetPlus/promax/controlnet_union_train_medical_image_restoration_fix_controlnet.py", line 1927, in main
    model_pred = unet(
  File "/home/heming/miniconda3/envs/controlplus/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/heming/miniconda3/envs/controlplus/lib/python3.8/site-packages/diffusers/models/unets/unet_2d_condition.py", line 1281, in forward
    sample = upsample_block(
  File "/home/heming/miniconda3/envs/controlplus/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/heming/miniconda3/envs/controlplus/lib/python3.8/site-packages/diffusers/models/unets/unet_2d_blocks.py", line 2541, in forward
    hidden_states = resnet(hidden_states, temb)
  File "/home/heming/miniconda3/envs/controlplus/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/heming/miniconda3/envs/controlplus/lib/python3.8/site-packages/diffusers/models/resnet.py", line 332, in forward
    hidden_states = self.norm1(hidden_states)
  File "/home/heming/miniconda3/envs/controlplus/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/heming/miniconda3/envs/controlplus/lib/python3.8/site-packages/torch/nn/modules/normalization.py", line 273, in forward
    return F.group_norm(
  File "/home/heming/miniconda3/envs/controlplus/lib/python3.8/site-packages/torch/nn/functional.py", line 2530, in group_norm
    return torch.group_norm(input, num_groups, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: mixed dtype (CPU): expect parameter to have scalar type of Float
```